### PR TITLE
Feature/cu m577qk update oni fang state machine

### PR DESCRIPTION
**Pull request by isaacfdez**

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-m577qk Update State Machine Fang & Onimaru](https://app.clickup.com/t/m577qk)

**Review by JoanMarcBardes — CHANGES_REQUESTED** [review]
The FrameRate from the clips of onimaru and fang need to update, be we have different numbers of keyframe this number for sure has changed.
For do that, you can go to the fbx.meta onimaru/fang and get de ID of the Clip and then search that ID on the Game/Library and inside of the JSON you will get the correct FrameRate for all the clips of the corresponding asset.

**Review by JoanMarcBardes — DISMISSED** [review]

**Review by Jordi-Gil — DISMISSED** [review]

**Review by saulzini — DISMISSED** [review]
Onimaru Hurt Clip it has an old animation UID 
Fang Dashes Clip has an old animation UID
I assume that these clips are not going to be used , so maybe for the next time we could delete them. For avoiding confussion

**Comment by isaacfdez** [comment]
> Onimaru Hurt Clip it has an old animation UID
> Fang Dashes Clip has an old animation UID
> I assume that these clips are not going to be used , so maybe for the next time we could delete them. For avoiding confussion

I made the changes, since Fang's dashes are indeed being used, but I removed the hurt clip from Onimaru since that won't be played anymore. Also changed the initial state of Fang's State Machine to Idle instead of RunLeft that it had before.

**Review by Jordi-Gil — APPROVED** [review]

**Review by JoanMarcBardes — APPROVED** [review]

**Review by saulzini — CHANGES_REQUESTED** [review]
I think it is missing to delete Onimaru Hurt dependencies in the state machine files from clips, states and transitions

**Review by saulzini — DISMISSED** [review]

**Review by Jordi-Gil — APPROVED** [review]

**Review by saulzini — APPROVED** [review]

**Review by JoanMarcBardes — APPROVED** [review]

**Pull request merged**
