### PR TITLE
now enemies dies when dissolve has finished

### PR DESCRIPTION
**Pull request by Yonimevicio**
CU-1ck5juu  Enemies do not perform death animation, or the disappear transition when a wave is completed. They all disappear 
CU-1dndn66 Spawners make enemies disappear before the death time
CU-1e103d7 Enemies don't get destroyed after they are killed (They still exist in the hierarchy)

Now, all problems should be fixed if the unlock time for all encounters is greater than the dissolve time of the enemies. 

First shot should be working correctly now (but still are a minor bug with a secondary state machine message on the console)

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1dndn66 Spawners make enemies disappear before the death time](https://app.clickup.com/t/1dndn66)

**Comment by jcarlos0305** [comment]
Task linked: [CU-1ck5juu Enemies do not perform death animation, or the disappear transition when a wave is completed. They all disappear instantly.](https://app.clickup.com/t/1ck5juu)

**Comment by jcarlos0305** [comment]
Task linked: [CU-1e103d7 Enemies don't get destroyed after they are killed (They still exist in the hierarchy)](https://app.clickup.com/t/1e103d7)

**Review by isaacfdez — DISMISSED** [review]

**Review by JaimeBea — APPROVED** [review]

**Review by FrancPS — APPROVED** [review]
When Onimaru is active for a while, it stops making damage to the enemies, but maybe that is not related to this branch.

What i've seen is that in the encounter in front of Cafeteria, when finishing the first wave there, some ranged enemies still don't do the animation...

**Pull request merged**
