### PR TITLE
Feature/cu jzactb spawn enemies on click

### PR DESCRIPTION
**Pull request by jcarlos0305**
Spawn enemies on click, but to avoid conflict when shooting, I set the combination of LSHIFT + LCTRL + click

https://user-images.githubusercontent.com/6886356/119225131-495b9700-bb02-11eb-9a85-0a7b6d4bc117.mp4

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-jzactb Spawn enemies by mouse click](https://app.clickup.com/t/jzactb)

**Review by isaacfdez — APPROVED** [review]

**Comment by GBMiro** [comment]
Spawn

Nice feature! I tested it in the level and saw that when spawning the models, they are set in a lower position respective the player but as the animation goes it eventually catches up.

Setting this new position to the same height as the player should do the trick

**Review by GBMiro — APPROVED** [review]

**Comment by jcarlos0305** [comment]
> Spawn
> 
> Nice feature! I tested it in the level and saw that when spawning the models, they are set in a lower position (the one on the right) respective the player but as the animation goes it eventually catches up.
> 
> Setting this new position to the same height as the player should do the trick

They are set at the same height as the GO with the script, we can either set that game object at the same height as the player when placing it, or you consider it useful that it should also receive the player GO and get its transform and do it programmatically?

**Comment by GBMiro** [comment]
> They are set at the same height as the GO with the script, we can either set that game object at the same height as the player when placing it, or you consider it useful that it should also receive the player GO and get its transform and do it programmatically?

As this is a debug functionality I think that setting the game object at the same height as the player is enough

**Pull request merged**
