### PR TITLE
Features/CU-1e10nhq_dialogues

### PR DESCRIPTION
**Pull request by FrancPS**
DIALOGUES COMPLETE FEATURES.

Added to the branch:
- Switch is blocked until tutorial is reached.
- Added a flash effect between talking characters
- Added audio support
- Adjusted dialogue texts to the dialogue window size

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1e10nhq Dialogues - Iteration 2](https://app.clickup.com/t/1e10nhq)

**Review by isaacfdez — DISMISSED** [review]

**Review by isaacfdez — APPROVED** [review]

**Review by JaimeBea — DISMISSED** [review]
Bugs found:
- You can dash through the triggers
  - This is a problem especially in the last dialogue, as you can dash directly to the next level
- Fang can switch to the shooting animation while inside a dialogue
- The dashing ability illuminates when pressing space inside a dialogue
- You can press R in the tutorial while the text is appearing and the dialogue won't disappear

**Comment by JaimeBea** [comment]
More bugs:

- Killing an enemy while inside a dialogue makes the enemy unkillable
  - Try shooting right before entering a dialogue or using any ultimate
- Error sounds when dialogues appear? Not sure if on purpose

**Comment by FrancPS** [comment]
Fixed all bugs but:

> Error sounds when dialogues appear? Not sure if on purpose
Yes, the sounds included are just placeholders

> You can dash through the triggers
> This is a problem especially in the last dialogue, as you can dash directly to the next level
This also happens in Cafeteria, with the switch tutorial.
I will wait for JuanCarlos's PR, this might be fixed there. not the bug itself, but how the dialogues and encounters are built

**Review by JaimeBea — APPROVED** [review]
Bugs;
- If you enter a dialogue while shooting you can keep shooting.
- Dashing through a dialogue will make you unable to act.
- Enemies will recieve damage from the ult just after the dialogue ends when ulting.

**Review by JaimeBea — APPROVED** [review]

**Review by devildrake — APPROVED** [review]

**Review by Mefiso — APPROVED** [review]

**Pull request merged**
