### PR TITLE
Factory doors, noodle shop power-up & plaza's rotating cube

### PR DESCRIPTION
**Pull request by jcarlos0305**
- Added the factory doors script that triggers the animation after the final dialog
- Updated the second power-up location to inside the cafeteria
- Added the cube rotation script to the cube in the plaza

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1dvckn8 Level1 Factory door animation integration with dialogues and Load Scene 2 trigger](https://app.clickup.com/t/1dvckn8)

**Review by Mefiso — DISMISSED** [review]
I would have preferred that the AfterDialogueCallback had a method witha generic name instead of the specific OpenFactoryDoors. That way you could implement other after dialogue callbacks without adding extra code in the TriggerDialogue. But taking into account the scope of this project I think it's okay.

**Review by Mefiso — APPROVED** [review]

**Comment by telmiuse** [comment]
image
i dont know why but there is a bugg

**Review by JaimeBea — APPROVED** [review]

**Comment by telmiuse** [comment]
Should have a collider on the end of level 1 inside the factory. This must be activated by the Wincodition. 
Also didnt appear correctly on the level 2 scene.

**Review by magalenyo — APPROVED** [review]

**Comment by magalenyo** [comment]
As Telm said, in this PR, the factory should have a trigger that loads Scene 2, but instead, it keeps the old wincon. This should've been changed in this PR, but to not further block Nil & Telm, let's do this in a different PR this afternoon.

**Pull request merged**
