### PR TITLE
Feature/cu 1da4wwz boss shield

### PR DESCRIPTION
**Pull request by devildrake**
Boss shield now activable through InitShield method. 
Can be toggled on and off with a bool on the bottom of the AIDuke script for debugging purposes.
Can be tested inside scene Level2_boss_shield.scene

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-p1btku Boss mechanics](https://app.clickup.com/t/p1btku)

**Comment by jcarlos0305** [comment]
Task linked: [CU-1da4wwz Implement Shield](https://app.clickup.com/t/1da4wwz)

**Review by magalenyo — APPROVED** [review]
You couldn't use the already existing Shield script?

**Review by Mefiso — APPROVED** [review]
Okay, so you created the ways for activating the shield, but you didn't put that activation on the ShieldShoot method. I'll do that in the BossBassicStructure branch, then.

**Pull request merged**
