### PR TITLE
Feature/cu 1e6jjft Level1 and Level2 merge and bugs

### PR DESCRIPTION
**Pull request by magalenyo**
This includes:

Level2:
- Player merge update (includes Telm's aim)
- Ranged prefab update
- Melee prefab update
- HUD update
- GameManager update

Level1:
- Player prefab  (includes Telm's aim)

BOTH LEVEL 1 AND 2 NEED TO HAVE THE AUDIOCONTROLLER ADDED AND CONFIGURED

Other And Bugs:
- Player aiming bug where it doesn't let you do any kind of cooldown because of the missing laser component
- Player Ultimate bug not hitting enemies
- Onimaru push
- Reload Button fix on level1 and level2
- Mouse cursor on level1 and level2

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1e6jjft Level 2 Merges and bug solving](https://app.clickup.com/t/1e6jjft)

**Comment by telmiuse** [comment]
oJ3GT3YWLN
Bugg on this part of the scene
Remember to put fbx boss

**Review by telmiuse — DISMISSED** [review]
oJ3GT3YWLN
Miss boss fbx

**Review by isaacfdez — APPROVED** [review]

**Comment by FrancPS** [comment]
Onimaru Blast does nothing to melee or ranged enemies spawned from debug.
Fang Ultimate does nothing to melee or ranged enemies spawned from debug.

**Comment by magalenyo** [comment]
@FrancPS Reviewed and solved for lvl1 and lvl2

**Review by FrancPS — APPROVED** [review]

**Review by jcarlos0305 — APPROVED** [review]

**Review by FrancPS — APPROVED** [review]

**Review by JaimeBea — DISMISSED** [review]

**Review by Yonimevicio — APPROVED** [review]

**Review by FrancPS — APPROVED** [review]

**Review by jcarlos0305 — APPROVED** [review]

**Review by JaimeBea — APPROVED** [review]

**Review by JaimeBea — APPROVED** [review]

**Pull request merged**
