### PR TITLE
Feature/cu 1da49r4 glitchy gif menu title

### PR DESCRIPTION
**Pull request by devildrake**
Established menu with glitchy title.
4 different animations (Title in, Idle, Glitch, Title out)
Established Fade to back on pressed Play, Can be tested in StartSceneGlitchyTitle.scene

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1da49r4 Replace Start Menu Shutdown icon with the new Glitchy Gif](https://app.clickup.com/t/1da49r4)

**Review by isaacfdez — DISMISSED** [review]

**Review by magalenyo — CHANGES_REQUESTED** [review]
Several things to review, it does not follow the Notes of the .txt file:
1- There's not fade in when on Level Start
2- Check LOGO VIBRATION Notes because there isn't any Sound playing atm. Use placeholders if needed.
3- LOGO OUTRO is not implemented
image

**Review by FrancPS — APPROVED** [review]

**Review by isaacfdez — APPROVED** [review]

**Comment by devildrake** [comment]
> Several things to review, it does not follow the Notes of the .txt file:
> 1- There's not fade in when on Level Start
> 2- Check LOGO VIBRATION Notes because there isn't any Sound playing atm. Use placeholders if needed.
> 3- LOGO OUTRO is not implemented
> image

Fade in established
Placeholders set, no clips on AudioSources yet, but AudioSources established
Logo outro was implemented, only that delay between it and the Fade out hadn't been set, this has been fixed

**Review by isaacfdez — DISMISSED** [review]

**Review by FrancPS — DISMISSED** [review]

**Review by magalenyo — APPROVED** [review]

**Review by magalenyo — DISMISSED** [review]
Nice feedback on animations and transition

**Review by FrancPS — APPROVED** [review]

**Review by isaacfdez — DISMISSED** [review]

**Review by magalenyo — CHANGES_REQUESTED** [review]
The background image on other Canvases that are not the First one seem to not have the image correctly set. Please, review them: 

image

It also doesn't have the fade in effect when comming back from other canvases.

Please review the changes, at least the background image on other canvases.

**Review by FrancPS — APPROVED** [review]

**Review by JaimeBea — APPROVED** [review]

**Review by jcarlos0305 — APPROVED** [review]

**Pull request merged**
