### PR TITLE
Feature/cu 1da4wyh calling troops

### PR DESCRIPTION
**Pull request by jcarlos0305**

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-p1btku Boss mechanics](https://app.clickup.com/t/p1btku)

**Comment by jcarlos0305** [comment]
Task linked: [CU-1da4wyh Implement calling troops](https://app.clickup.com/t/1da4wyh)

**Review by isaacfdez — APPROVED** [review]

**Review by Mefiso — CHANGES_REQUESTED** [review]
Okay, just to be clear. There should be 4 encounters, 2 on phase 2 and 2 on phase 3. And I would like that the logic of activating the troops inside the CallTroops method (just to leave the Update as clear as possible).

**Comment by Mefiso** [comment]
Also, if you can, try to include in this PR the functionality of returning the Boss to the field when an encounter is finished (and delete the fake troops counter on the Update of AIDuke.cpp)

**Review by devildrake — APPROVED** [review]

**Pull request merged**
