### PR TITLE
Feature/cu 1e6nwjw spots effect

### PR DESCRIPTION
**Pull request by telmiuse**
task linked : https://app.clickup.com/t/1e6nwjw

### CODE REVIEW

**Comment by jcarlos0305** [comment]
Task linked: [CU-1e6nwjw Spots Motion Effect](https://app.clickup.com/t/1e6nwjw)

**Comment by telmiuse** [comment]
https://i.imgur.com/AUtfV4W.gif

**Comment by telmiuse** [comment]
gif

**Comment by telmiuse** [comment]
You chan check this on AdvertScene

**Pull request closed without merging**
