### PR TITLE
Lvl1 merge bugs

### PR DESCRIPTION
**Pull request by lowysole**

### CODE REVIEW

**Comment by Jordi-Gil** [comment]
Toggle enemies is broken.

**Review by Jordi-Gil — APPROVED** [review]
If you press Toggle Enemies in debug mode, the spawn pointers and dialogues not working properly. Approved cause is something related to Debug Mode.

**Review by devildrake — DISMISSED** [review]

**Review by Jordi-Gil — DISMISSED** [review]

**Review by devildrake — DISMISSED** [review]
I tried to load level1 a total of 6 times, I reloaded library 4 times, at the 6th time, the engine didn't crash, the other 5 times, every single level1 load crashed the engine, this is really scary.

**Review by telmiuse — APPROVED** [review]

**Review by devildrake — APPROVED** [review]
Now that loading scene 1 doesn't crash it's great. Approved.

**Review by Jordi-Gil — APPROVED** [review]

**Pull request merged**
